package com.company.server.enums;
//Akmal aka
public enum State {
    PHONE_NUMBER, MAIN_PAGE, CHOOSE_CATEGORY, ENTER_CATEGORY_NAME, ENTER_PRODUCT_NAME, CHOOSE_PRODUCT, ENTER_PRODUCT_PRICE, ENTER_PRODUCT_URL, ENTER_NAME

}
