package com.company.server.enums;

public enum State {
    CHOOSE_ORDER,
    PHONE_NUMBER,
    MAIN_PAGE,
    CHOOSE_CATEGORY,
    ENTER_CATEGORY_NAME,
    ENTER_PRODUCT_NAME,
    CHOOSE_PRODUCT,
    ENTER_PRODUCT_PRICE,
    ENTER_PRODUCT_URL,
    CHOOSE,
    CHOOSE_COUNT,
    DELETE_CATEGORY,
    CREATE_CHILD_CATEGORY,
    DELETE_CHILD_CATEGORY,
    SEND_PHOTO,
    SEND_PRODUCT_PRICE,
    ENTER_NAME, START,

}

